# 가독성과 구조적 유연성, spring boot와의 연결을 위한 YAML 사용
# 공통 설정. DB 접속 정보는 application-local.yml에 작성
spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
